# Vicinae Matugen Ultimate Theme
# Masterfully crafted Material You theme with perfect interaction design
# Every decision backed by Material Design 3 principles

[meta]
name = "Matugen Ultimate"
description = "Perfectly balanced Material You theme - {{mode}} variant"
variant = "{{mode}}"
icon = "noctalia.svg"

# ============================================================================
# Core Colors - Material 3 Foundation
# ============================================================================

[colors.core]
accent = "{{colors.primary.default.hex}}"
accent_foreground = "{{colors.on_primary.default.hex}}"
background = "{{colors.surface.default.hex}}"
foreground = "{{colors.on_surface.default.hex}}"
secondary_background = "{{colors.surface_container.default.hex}}"
border = "{{colors.outline_variant.default.hex}}"

# ============================================================================
# Window Borders - Contextual Hierarchy
# ============================================================================

[colors.main_window]
border = "{{colors.outline_variant.default.hex}}"  # Softer for main app

[colors.settings_window]
border = "{{colors.outline.default.hex}}"  # Stronger but not primary (less distracting)

# ============================================================================
# Accent Palette - Full Spectrum Harmony
# ============================================================================

[colors.accents]
blue = "{{colors.primary.default.hex}}"
green = "{{colors.tertiary.default.hex}}"
magenta = "{{colors.secondary.default.hex}}"
orange = { name = "{{colors.error.default.hex}}", lighter = 40 }  # Warmer, less alarming
red = "{{colors.error.default.hex}}"
yellow = { name = "{{colors.tertiary.default.hex}}", lighter = 80 }  # Bright and cheerful
cyan = { name = "{{colors.primary.default.hex}}", lighter = 50 }  # Cool and distinct
purple = "{{colors.secondary.default.hex}}"

# ============================================================================
# Text System - Semantic Perfection
# ============================================================================

[colors.text]
default = "{{colors.on_surface.default.hex}}"
muted = "{{colors.on_surface_variant.default.hex}}"
danger = "{{colors.error.default.hex}}"  # Direct error color for text
success = "{{colors.tertiary.default.hex}}"  # Direct tertiary for success text
placeholder = { name = "{{colors.on_surface_variant.default.hex}}", opacity = 0.6 }  # More subtle

[colors.text.selection]
background = "{{colors.primary.default.hex}}"
foreground = "{{colors.on_primary.default.hex}}"

[colors.text.links]
default = "{{colors.primary.default.hex}}"
visited = { name = "{{colors.tertiary.default.hex}}", darker = 20 }  # Distinct shift, not just darker primary

# ============================================================================
# Input Fields - Clear States
# ============================================================================

[colors.input]
border = "{{colors.outline.default.hex}}"
border_focus = "{{colors.primary.default.hex}}"
border_error = "{{colors.error.default.hex}}"

# ============================================================================
# Buttons - Material 3 Elevation
# ============================================================================

[colors.button.primary]
background = "{{colors.surface_container_high.default.hex}}"  # Elevated but neutral
foreground = "{{colors.on_surface.default.hex}}"

[colors.button.primary.hover]
background = "{{colors.surface_container_highest.default.hex}}"  # One level up in elevation

[colors.button.primary.focus]
outline = "{{colors.primary.default.hex}}"  # Primary for focus clarity

# ============================================================================
# Lists - Interaction Gradient
# ============================================================================
# Hover → Selection creates smooth visual progression

[colors.list.item.hover]
background = { name = "{{colors.primary_container.default.hex}}", opacity = 0.25 }  # Whisper of primary
foreground = "{{colors.on_surface.default.hex}}"

[colors.list.item.selection]
background = { name = "{{colors.primary_container.default.hex}}", opacity = 0.65 }  # Strong but not solid
foreground = "{{colors.on_primary_container.default.hex}}"
secondary_background = "{{colors.primary_container.default.hex}}"  # Full opacity on elevated surfaces
secondary_foreground = "{{colors.on_primary_container.default.hex}}"

# ============================================================================
# Grid Items - Bold Visual Language
# ============================================================================

[colors.grid.item]
background = "{{colors.surface_container.default.hex}}"

[colors.grid.item.hover]
outline = { name = "{{colors.secondary.default.hex}}", opacity = 0.8 }  # Secondary for hover differentiation

[colors.grid.item.selection]
outline = { name = "{{colors.primary.default.hex}}" }  # Full primary, no opacity - maximum clarity

# ============================================================================
# Scrollbars - Minimal but Themed
# ============================================================================

[colors.scrollbars]
background = { name = "{{colors.primary.default.hex}}", opacity = 0.2 }  # Subtly themed

# ============================================================================
# Loading States - Consistent Accent
# ============================================================================

[colors.loading]
bar = "{{colors.primary.default.hex}}"
spinner = "{{colors.primary.default.hex}}"
